[images]
  remote_images = ["https://source.unsplash.com/.*", "https://images.unsplash.com/.*", "https://ext.same-assets.com/.*", "https://ugc.same-assets.com/.*"]

[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  SECRETS_SCAN_SMART_DETECTION_ENABLED = "false"

[[plugins]]
  package = "@netlify/plugin-nextjs"
